# Configuration for different environments

server:
  port: "8084"
  host: "localhost"

database:
  driver: "sqlite"    # or "postgres"
  dsn: "coin_indexer.db"
  # For PostgreSQL:
  # driver: "postgres"
  # dsn: "host=localhost user=username password=password dbname=coin_indexer port=5432 sslmode=disable"

blockchain:
  provider_url: "ws://localhost:8545"  # Local node
  # Alternative providers:
  # provider_url: "wss://mainnet.infura.io/ws/v3/YOUR_INFURA_PROJECT_ID"
  # provider_url: "wss://eth-mainnet.alchemyapi.io/v2/YOUR_ALCHEMY_KEY"
  
  # Block confirmation depth for finality
  confirmation_blocks: 12
  
  # Polling interval for new blocks (in seconds)
  poll_interval: 15

contracts:
  # List of token contracts to monitor
  tokens:
    - name: "USDC"
      address: "0xA0b86a33E6417AaF4532CfAd6F41F68481a66CD1"
      start_block: 18500000  # Block to start indexing from
      abi_file: "abis/erc20.json"
    - name: "USDT"
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      start_block: 18500000
      abi_file: "abis/erc20.json"
    - name: "GETH"
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" 
      start_block: 1
      abi_file: "abis/erc20.json"
    # Add more contracts as needed

indexing:
  # Number of blocks to process in parallel
  batch_size: 100
  
  # Maximum number of retries for failed operations
  max_retries: 3
  
  # Delay between retries (in seconds)
  retry_delay: 5

logging:
  level: "info"     # debug, info, warn, error
  format: "json"    # json or text